const SUPABASE_URL='https://qykwrgorpoqrjwxipiig.supabase.co';
const SUPABASE_KEY='sb_publishable_bX-p3X9diV9i8svHqbv65w_pVcc8Y9c';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);

const sets={
'Random 😂':[
'What completely pointless thing are you weirdly good at?','What tiny inconvenience turns you into an unreasonable person?','What food opinion would you defend far too aggressively?','What is the strangest thing currently in your camera roll?','What would your warning label say?','What very normal thing are you inexplicably terrible at?','What would you buy immediately if somebody handed you £50 and said you had to waste it?','What phrase do you say far too much?','What harmless thing gives you the ick for absolutely no good reason?','What ridiculous hill would you happily die on?','What is the weirdest thing you believed for far too long?','What everyday object do you have an unnecessarily strong opinion about?','If your search history from today was a personality test, what would it conclude?','What is the most useless fact permanently lodged in your brain?','What is something you always lose even though it has an obvious home?','What is your most chaotic cooking habit?','Which animal do you think would personally dislike you?','What is the stupidest injury you have ever given yourself?','What is your most embarrassing autocorrect or accidental message?','What is something everyone seems to enjoy that you simply do not understand?','If you had to give a TED Talk with zero preparation, what could you talk about for 20 minutes?','What is the pettiest reason you have ever disliked something?','Which household chore do you treat like a personal attack?','What is the most ridiculous thing you have bought and still defend?','If you were banned from your usual job tomorrow, what wildly unsuitable career would you try?','What smell do you secretly love that probably should not smell good?','What would instantly expose you if someone impersonated you for a day?','What is your most irrational superstition or little ritual?','If your life had a useless achievement badge, what would you have unlocked?','What is one thing you would absolutely cheat at if there were no consequences?'
],
'Actually Interesting':[
'When do you feel most like yourself?','What do people tend to misunderstand about you?','What tiny thing makes you disproportionately happy?','What makes you feel genuinely looked after?','What do you need quite a lot of but rarely actually ask for?','What kind of day quietly resets you?','What is something you’ve become much softer about with age?','What is one thing you wish people understood about you without needing it explained?','What makes you trust somebody?','What is something about yourself you understand much better now than five years ago?','What makes you feel safe enough to properly relax around somebody?','What kind of silence feels comfortable to you?','What is something you have stopped apologising for?','What do you notice about people that others often miss?','What makes you feel appreciated without anybody actually saying thank you?','What is something you protect more carefully now than you used to?','When you are overwhelmed, what actually helps rather than what people assume helps?','What kind of attention makes you feel seen?','What part of your personality only appears around people you really trust?','What do you wish you were better at asking for?','What is one boundary you learned the hard way?','What kind of person brings out your most playful side?','What makes somewhere feel like home to you?','What is something you value much more now than you did ten years ago?','What kind of conversation can keep you awake far too late?','What is one thing you think people learn about you slowly?','What is something you are proud of that probably looks small from the outside?','What makes you emotionally retreat from somebody?','What helps you come back when you have gone quiet?','What is something you would rather somebody notice than have to ask for?'
],
'Memories 🫶':[
'What childhood smell immediately takes you somewhere?','What completely ordinary memory would you happily relive?','Which younger version of yourself would you most like to spend an hour with?','What old photo of you tells a story nobody else would know from looking at it?','What is a tiny tradition you would hate to lose?','What song belongs to a particular time of your life?','What did you love as a child that you still love now?','What memory makes you laugh before you’ve even finished telling it?','What is one place you remember mainly by how it felt?','What moment do you wish you’d photographed?','What meal instantly reminds you of somebody?','What was your favourite hiding place as a child?','What is the earliest memory you can picture clearly?','What childhood possession would you love to find again?','What was the first thing you remember saving your own money to buy?','Who made you laugh most when you were growing up?','What ordinary sound takes you straight back to childhood?','What school memory still makes you cringe?','What is a memory you did not realise was special until much later?','What is the best spontaneous day you can remember?','What journey or car ride do you remember unusually clearly?','What was your comfort TV programme or film growing up?','What is something a family member used to say that you can still hear in their voice?','What was your first proper taste of independence?','What birthday do you remember most clearly and why?','What is one memory you wish you could see from somebody else’s perspective?','What place from your past would you like to walk through exactly as it was then?','What is a tiny kindness somebody showed you years ago that you still remember?','What phase of your life had the best soundtrack?','What memory feels completely insignificant but you would hate to lose?'
],
'Us 👀':[
'What did you initially assume about me that turned out to be wrong?','What is something about me you noticed before I realised you had?','Which memory of us makes you laugh fastest?','What is the most random thing that has somehow become “our thing”?','What is one thing you think we’re unexpectedly good at together?','What do you think I understand about you better than most people?','What is one tiny thing I do that feels very “me” to you?','What is something about us you genuinely didn’t expect?','What is something you would actually miss if we stopped doing it?','What is one thing about me you think I still don’t realise?','What is the first conversation with me you remember properly?','When did you first realise I was not quite what you expected?','What is something I do that reliably makes you laugh?','What do you think is the strangest thing we have managed to make completely normal?','What is a moment with me that felt unexpectedly easy?','What is something you know will immediately make you think of me?','What is something we could probably turn into an inside joke within five minutes?','Which version of me do you find funniest?','What is one thing you think I can read on your face without you saying it?','What is something you think I pretend not to notice about you?','What is a completely mundane thing you would happily do together again?','What do you think we communicate surprisingly well without words?','What is one thing I have introduced you to that stuck?','What is a question you have wanted to ask me but never found a natural moment for?','What do you think is our most ridiculous recurring conversation?','What is one way we are more alike than you expected?','What is one way we are completely different that somehow works?','What moment between us would make absolutely no sense to anybody else?','What is something I have said that you remember more clearly than I probably do?','What do you think I notice about you first when I see you?','What do you notice about me first when you see me?','What is one thing you think I bring out in you?','What do you think you bring out in me?','What is something you would trust me to choose for you without asking?','What is a place or thing you would genuinely like to show me one day?','What is something about me that became more obvious the longer you knew me?','What kind of trouble do you think we are most likely to accidentally get into together?','What is the nicest ordinary moment we have had?','What is something you think we would be terrible at doing together?','What is something you think we would be dangerously good at doing together?'
],
'Would You Rather':[
'Disappear somewhere for a weekend or stay in bed all day?','Know exactly what I am thinking for ten minutes or absolutely never know?','Have an amazing plan or accidentally have an amazing day?','Replay one perfect day or erase one terrible one?','Always say exactly what you mean or always know exactly what the other person means?','Be able to pause time or rewind ten minutes once a day?','Have unlimited money for travel or unlimited free time?','Give up music for a month or your phone for a week?','Live somewhere beautiful but remote or chaotic but full of life?','Be hilariously overdressed or painfully underdressed?','Have somebody cook your favourite meal or plan your perfect day?','Always arrive thirty minutes early or ten minutes late?','Be able to read minds or make people forget one thing?','Have a photographic memory or be able to forget anything on command?','Spend a week somewhere you have never been or revisit somewhere you love?','Always know when somebody is lying or always know why they are lying?','Lose your sense of taste for a month or your phone for a month?','Have one extra hour every day or one extra day every month?','Be stuck together in an airport overnight or on a broken-down train for six hours?','Have to sing everything you mean or mime everything important?','Know exactly how your life looks in ten years or keep it completely unknown?','Have your thoughts accidentally appear as subtitles or your camera roll displayed publicly for ten minutes?','Be brilliant at something useless or average at everything useful?','Get £10,000 today or a guaranteed brilliant surprise every year for ten years?','Be able to teleport anywhere but only once a week or fly but only at jogging speed?','Never have to sleep or always have perfect sleep?','Have a house by the sea or a hidden cabin in the woods?','Be forced to answer one question completely honestly or ask one question that has to be answered honestly?','Have a rewind button for conversations or a mute button for people?','Share a tiny hotel room or accidentally book separate hotels on opposite sides of a city?'
],
'Dangerous 😈':[
'What kind of compliment actually gets to you?','What is something somebody can do that you find ridiculously attractive?','What creates chemistry for you that has nothing to do with looks?','What kind of physical affection do you never really get bored of?','What is something innocent your brain regularly makes inappropriate?','What makes flirting fun rather than awkward for you?','What is one thing you find attractive that would probably surprise people?','What is the closest you’ve come to saying something to me and stopping yourself?','What is something about our chemistry you find funny?','What question were you secretly hoping I’d ask you?','What is more attractive to you: confidence, softness or mischief?','What kind of eye contact gets dangerous?','What tiny physical detail do you tend to notice about somebody you fancy?','What is something completely non-sexual that can somehow feel intimate?','What kind of touch gets your attention immediately?','What makes a hug go from normal to very much not normal?','What is the difference between somebody being attractive and you actually wanting them?','What is something somebody can whisper that would instantly ruin your ability to behave?','Do you prefer obvious flirting or the kind where nobody admits it is flirting?','What is the most dangerous kind of silence between two people?','What is something you would find much harder to resist than you would like to admit?','What kind of tension is more fun: obvious or deniable?','What is one thing that becomes much more attractive when you already like somebody?','What is the boldest thing somebody could do that you would secretly love?','What is your favourite kind of kiss: soft, playful, slow or the kind that ruins the question?','What makes somebody’s voice suddenly attractive?','What kind of closeness makes you forget what you were talking about?','What is more intimate to you than people generally realise?','What is something you could probably communicate with one look?','What is the most unfairly attractive thing a person can wear?','What is one innocent situation that has absolutely no business feeling sexy?','What kind of teasing actually works on you?','What is something you would be more likely to do than admit you wanted to do?','What makes anticipation better than the actual moment sometimes?','What is the line between playful and genuinely flustered for you?','What is one thing that can make you blush even when you know exactly what is happening?','What is something you have imagined and immediately told your brain to shut up about?','What is the most distracting thing somebody can do while sitting right beside you?','What would make you instantly aware of how close somebody was standing?','What kind of affection feels the most difficult to pretend is casual?'
]};

let selected='Random 😂', state=null, game=null, secret=null, player=null, poller=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function msg(t){$('#toast').textContent=t||''}
function randSecret(){const a=new Uint8Array(24);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
function params(){const u=new URL(location.href);return {room:u.searchParams.get('room'),s:u.searchParams.get('s'),p:Number(u.searchParams.get('p'))||null}}
function usedQuestions(){return new Set((state?.history||[]).map(x=>x.question))}
function pickQuestion(){const used=usedQuestions();let pool=sets[selected].filter(x=>!used.has(x));if(!pool.length) pool=[...sets[selected]];return pool[Math.floor(Math.random()*pool.length)]}
function shareUrlFor(p){const u=new URL(location.href);u.search='';u.searchParams.set('room',game);u.searchParams.set('s',secret);u.searchParams.set('p',p);return u.toString()}
function pausedKey(){return game?`fmot:paused:${game}:${player}`:null}
async function createGame(){const p1=$('#p1').value.trim()||'Ange',p2=$('#p2').value.trim()||'Vee';secret=randSecret();msg('Making trouble…');const {data,error}=await sb.rpc('fm_create_game',{p_secret:secret,p1,p2});if(error){msg('Database not ready yet — run the SQL setup first.');return}game=data;player=1;history.replaceState({},'',shareUrlFor(1));localStorage.setItem('fmot:'+game,'1');localStorage.removeItem(pausedKey());await refresh();startPolling();msg('Made 😈 Send Vee the invite link.');}
async function refresh(){if(!game||!secret||!player)return;const {data,error}=await sb.rpc('fm_state',{p_game:game,p_secret:secret,p_player:player});if(error){msg('Couldn’t load the game.');return}state=data;renderGame();}
function startPolling(){if(poller)clearInterval(poller);poller=setInterval(refresh,3500)}
function stopPolling(){if(poller){clearInterval(poller);poller=null}}
async function newQuestion(){const q=pickQuestion();msg('Picking trouble…');const {error}=await sb.rpc('fm_new_question',{p_game:game,p_secret:secret,p_category:selected,p_question:q});if(error){msg(error.message.includes('Finish')?'Answer or skip this one first 😂':'Couldn’t pick a question.');return}await refresh();}
async function submitAnswer(){const cur=state?.current;if(!cur)return;const ans=$('#answer').value.trim();if(!ans){msg('You do actually have to type something 😂');return}$('#submit').disabled=true;const {error}=await sb.rpc('fm_submit_answer',{p_game:game,p_secret:secret,p_question:cur.id,p_player:player,p_answer:ans});$('#submit').disabled=false;if(error){msg('That answer refused to cooperate.');return}msg('Locked 🔒 Waiting for the other answer…');await refresh();}
async function skip(){const cur=state?.current;if(!cur)return;await sb.rpc('fm_skip_question',{p_game:game,p_secret:secret,p_question:cur.id});msg('Skipped. No explanation required 😌');state.current=null;renderGame();}
async function shareInvite(){const other=player===1?2:1;const url=shareUrlFor(other);const text=`Five Minutes of Trouble 😈\n${url}`;if(navigator.share){try{await navigator.share({text});return}catch(e){}}await navigator.clipboard.writeText(text);msg('Invite copied — paste into WhatsApp 😈')}
function pauseGame(){localStorage.setItem(pausedKey(),'1');stopPolling();$('#game').hidden=true;$('#paused').hidden=false;msg('');}
async function resumeGame(){localStorage.removeItem(pausedKey());$('#paused').hidden=true;$('#game').hidden=false;await refresh();startPolling();}
function renderCats(){const c=$('#cats');c.innerHTML='';Object.keys(sets).forEach(n=>{const b=document.createElement('button');b.className='cat'+(n===selected?' on':'');b.textContent=n;b.onclick=()=>{selected=n;renderCats()};c.appendChild(b)})}
function historyHtml(){const rows=(state?.history||[]).filter(x=>!x.skipped&&x.player1_answer&&x.player2_answer);if(!rows.length)return '<p class="muted">Nothing revealed yet. Suspiciously innocent.</p>';return rows.map(x=>`<div class="historyItem"><div class="small">${esc(x.category)}</div><b>${esc(x.question)}</b><div class="answerBox"><strong>${esc(state.player1_name)}</strong><br>${esc(x.player1_answer)}</div><div class="answerBox"><strong>${esc(state.player2_name)}</strong><br>${esc(x.player2_answer)}</div></div>`).join('')}
function renderGame(){renderCats();$('#setup').hidden=true;$('#game').hidden=false;$('#paused').hidden=true;$('#who').textContent=`You’re ${player===1?state.player1_name:state.player2_name}`;$('#historyList').innerHTML=historyHtml();const cur=state.current;if(!cur||cur.skipped){$('#question').textContent='Pick a category and cause a little trouble.';$('#category').textContent='READY WHEN YOU ARE';$('#answerArea').hidden=true;$('#reveal').hidden=true;$('#next').hidden=false;$('#skip').hidden=true;return}$('#category').textContent=cur.category.toUpperCase();$('#question').textContent=cur.question;$('#skip').hidden=false;if(cur.both_submitted){$('#answerArea').hidden=true;$('#reveal').hidden=false;$('#next').hidden=false;$('#a1').innerHTML=`<strong>${esc(state.player1_name)}</strong><br>${esc(cur.player1_answer)}`;$('#a2').innerHTML=`<strong>${esc(state.player2_name)}</strong><br>${esc(cur.player2_answer)}`;msg('Both answers unlocked 😈');}else{$('#reveal').hidden=true;$('#next').hidden=true;$('#answerArea').hidden=false;const mine=cur.my_answer;if(mine){$('#answer').value=mine;$('#answer').disabled=true;$('#submit').hidden=true;$('#waiting').hidden=false;$('#waiting').textContent=cur.partner_submitted?'Both are in… revealing 👀':'Yours is locked 🔒 Waiting for them…';}else{$('#answer').value='';$('#answer').disabled=false;$('#submit').hidden=false;$('#waiting').hidden=true;}}}
function init(){renderCats();const p=params();game=p.room;secret=p.s;player=p.p||Number(localStorage.getItem('fmot:'+game));if(game&&secret&&[1,2].includes(player)){localStorage.setItem('fmot:'+game,String(player));if(localStorage.getItem(pausedKey())==='1'){$('#setup').hidden=true;$('#game').hidden=true;$('#paused').hidden=false;}else{refresh();startPolling()}}else{$('#setup').hidden=false;$('#game').hidden=true;$('#paused').hidden=true}$('#create').onclick=createGame;$('#next').onclick=newQuestion;$('#submit').onclick=submitAnswer;$('#skip').onclick=skip;$('#share').onclick=shareInvite;$('#historyBtn').onclick=()=>$('#history').classList.toggle('open');$('#pause').onclick=pauseGame;$('#resume').onclick=resumeGame;}
window.addEventListener('DOMContentLoaded',init);
